### ISSUE TITLE
blender 2.8 cursor_location

### ISSUE THREAD

**Issue by j2l** [revpriest/blenderquicktalk#1]
As I wrote as comments on your website:

 j2l on June 7, 2019 at 12:22 pm said:
Hi,
I’m trying to achieve the same thing on Blender 2.8 but cursor_location is gone.
See https://blender.stackexchange.com/questions/134313/cursor-location-scene-blender-2-8

changing lines 320-322 to
x = bpy.context.scene.cursor.location[0];
y = bpy.context.scene.cursor.location[1];
z = bpy.context.scene.cursor.location[2];

works

**Comment by revpriest** [comment]
Thanks, might be in a position to look at it early next week.

**Comment by revpriest** [comment]
Sorry it took so long to get to this, but I've made that correction to the script now.

Thanks for pointing out the bug to me.
