### ISSUE TITLE
Does not work in Blender 4

### ISSUE THREAD

**Issue by NProsp** [revpriest/blenderquicktalk#2]
Could you please update this add-on to work in Blender 4

**Comment by revpriest** [comment]
Ah, doesn't work in 4 eh?

Can't make any promises without knowing why but I'll see if I can take a look, probably at the weekend. Would be good to have it working with the latest Blender for sure.

**Comment by revpriest** [comment]
Looks like the issue was that the parameters for the keyframe insertion can't be implied any more and have to be named. Dunno why they'd make that change. There's a QuickTalk4.py file now which does seem to work with V4 on my machine at least.
